djhex/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'polls'  # pylint: disable=invalid-name
urlpatterns = [  # pylint: disable=invalid-name
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

polls/views.py
# -*- coding: utf-8 -*-
# pylint: disable=unused-argument
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from polls.application import polls_controller
from polls.application.polls_view import PollsView
from polls.application.serializers import ChoiceSerializer, QuestionSerializer
from polls.framework import get_default_store
from polls.models import Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    store = get_default_store()
    is_json = request.META.get('HTTP_ACCEPT', None) == 'application/json'
    view = PollsJSONView(request, store) if is_json else PollsHTMLView(request)
    return polls_controller.vote(store, view, question_id, request.POST.get('choice', -1))


class PollsHTMLView(PollsView):

    def __init__(self, request):
        self.request = request

    def log_exception(self, exception):
        raise Http404 from exception

    def ask_question(self, question, error_message=None):
        return render(self.request, 'polls/detail.html', {
            'question': question,
            'error_message': error_message,
        })

    def list_results(self, question):
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class PollsJSONView(PollsView):

    def __init__(self, request, store):
        self.request = request
        self.store = store

    def log_exception(self, exception):
        return JsonResponse({"error": str(exception)}, status=404)

    def ask_question(self, question, error_message=None):
        choices = self.store.questions.get_choices(question)
        data = {
            "question": QuestionSerializer(question).data,
            "choices": [ChoiceSerializer(choice, fields=('id', 'choice_text',)).data for choice in choices]
        }
        status_code = 200
        if error_message:
            data['error_message'] = error_message
            status_code = 400
        return JsonResponse(data, status=status_code)

    def list_results(self, question):
        choices = self.store.questions.get_choices(question)
        return JsonResponse({
            "question": QuestionSerializer(question).data,
            "choices": [ChoiceSerializer(choice).data for choice in choices]
        })

polls/templates/polls/base.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<div id="content" class="container">
    <div class="page-header">
        <h1>{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}</h1>
    </div>

    {% block content %}{% endblock %}
</div>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    <form action="{% url 'polls:vote' question.id %}" method="post" class="form">
    {% csrf_token %}
        <div class="form-group">
        {% for choice in question.choice_set.all %}
        <div class="radio">
            <label for="choice{{ forloop.counter }}">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
                {{ choice.choice_text }}
            </label>
        </div>
        {% endfor %}
        </div>
    <input type="submit" value="Vote" class="btn btn-primary"/>
    </form>

{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

    <ul class="list-group">
    {% for choice in question.choice_set.all %}
        <li class="list-group-item">
            <span class="badge">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
            {{ choice.choice_text }}
        </li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detail' question.id %}" class="btn btn-default">Vote again?</a>

{% endblock %}